codecov:
  require_ci_to_pass: yes
  disable_default_path_fixes: true

coverage:
  precision: 2
  round: down
  range: "92...100"

  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: 100%
fixes:
  - "/home/runner/work/distributed::"

comment: off
